#include "unity.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "binomial.h"
#include "chi_squared.h"
#include "f.h"
#include "normal.h"
#include "poisson.h"
#include "t.h"

/* Tolerances chosen to be permissive for numerical quadratures */
static const double EPS = 1e-6;

/* Helper: read reference file (generated by SciPy) */
static int get_expected(const char *name, const char *args, double *out) {
    char line[256];
    if (!name || !out) return 0;
    if (!args) args = "";

#ifdef REFERENCE_FILE_PATH
    const char *ref_path = REFERENCE_FILE_PATH;
#else
    const char *ref_path = "tests/reference_values.txt";
#endif
    FILE *ref = fopen(ref_path, "r");
    if (!ref) {
        char msg[256];
        snprintf(msg, sizeof(msg), "Missing %s — run: cmake --build build --target generate_reference && cmake --build build --target test_runner", ref_path);
        TEST_FAIL_MESSAGE(msg);
        return 0;
    }

    while (fgets(line, sizeof(line), ref)) {
        /* line format: key args... value */
        char key[128];
        double val;
        /* Extract last token as value */
        char *last_space = strrchr(line, ' ');
        if (!last_space) continue;
        val = atof(last_space + 1);
        *last_space = '\0';
        /* now line has "key args..." */
        if (strcmp(line, name) == 0 || strstr(line, name) == line) {
            /* match beginning; ensure args match if provided */
            if (args[0] == '\0' || strstr(line, args) != NULL) {
                *out = val;
                fclose(ref);
                return 1;
            }
        }
    }
    fclose(ref);
    TEST_FAIL_MESSAGE("Reference value not found in tests/reference_values.txt");
    return 0;
}

/* setUp/tearDown are provided by the test runner */

void test_binomial_examples(void) {
    double expected;
    if (!get_expected("binompmf", "5 3 0.7", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(EPS, expected, binompmf(5, 3, 0.7));

    if (!get_expected("binomcdf", "6 2 0.7", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(EPS, expected, binomcdf(6, 2, 0.7));

    if (!get_expected("binompmf", "100 50 0.7", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(1e-5, expected, binompmf(100, 50, 0.7));

    if (!get_expected("binomcdf", "100 50 0.7", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(1e-5, expected, binomcdf(100, 50, 0.7));
}

void test_chi_squared_examples(void) {
    double expected;
    if (!get_expected("X2pdf", "5 3", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(5e-4, expected, X2pdf(5, 3));

    if (!get_expected("X2cdf", "5 3", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(5e-4, expected, X2cdf(5, 3));
}

void test_f_distribution_examples(void) {
    double expected;
    if (!get_expected("fpdf", "3 5 4", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(EPS, expected, fpdf(3, 5, 4));

    if (!get_expected("fcdf", "3 5 4", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(1e-4, expected, fcdf(3, 5, 4));
}

void test_normal_examples(void) {
    double expected;
    if (!get_expected("normalpdf_std", "0", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(EPS, expected, normalpdf_std(0));

    if (!get_expected("normalpdf_std", "1.5", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(EPS, expected, normalpdf_std(1.5));

    if (!get_expected("normalpdf", "0 0 1", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(EPS, expected, normalpdf(0, 0, 1));

    if (!get_expected("normalpdf", "2 1 2", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(EPS, expected, normalpdf(2, 1, 2));

    if (!get_expected("normalcdf_std", "-1 1", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(5e-4, expected, normalcdf_std(-1, 1));

    if (!get_expected("normalcdf", "-1 1 1 2", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(EPS, expected, normalcdf(-1, 1, 1, 2));
}

void test_poisson_examples(void) {
    double expected;
    if (!get_expected("poissonpmf", "3 5", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(EPS, expected, poissonpmf(3, 5));

    if (!get_expected("poissoncdf", "3 5", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(EPS, expected, poissoncdf(3, 5));
}

void test_student_t_examples(void) {
    double expected;
    if (!get_expected("tpdf", "3 5", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(1e-5, expected, tpdf(3, 5));

    if (!get_expected("tcdf", "3 5", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(5e-4, expected, tcdf(3, 5));

    if (!get_expected("tcdf", "0.5 5", &expected)) { TEST_IGNORE_MESSAGE("reference generator unavailable"); }
    TEST_ASSERT_DOUBLE_WITHIN(5e-4, expected, tcdf(0.5, 5));
}
